WebApplication9/Controllers/JuradoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication9.Models;

namespace WebApplication9.Controllers
{
    public class JuradoesController : Controller
    {
        private readonly SistemaDeConcursosContext _context;

        public JuradoesController(SistemaDeConcursosContext context)
        {
            _context = context;
        }

        // GET: Juradoes
        public async Task<IActionResult> Index()
        {
            var sistemaDeConcursosContext = _context.Jurados.Include(j => j.IdConcursoNavigation).Include(j => j.IdUsuarioNavigation);
            return View(await sistemaDeConcursosContext.ToListAsync());
        }

        // GET: Juradoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jurado = await _context.Jurados
                .Include(j => j.IdConcursoNavigation)
                .Include(j => j.IdUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.IdJurado == id);
            if (jurado == null)
            {
                return NotFound();
            }

            return View(jurado);
        }

        // GET: Juradoes/Create
        public IActionResult Create()
        {
            ViewData["IdConcurso"] = new SelectList(_context.Concursos, "IdConcurso", "IdConcurso");
            ViewData["IdUsuario"] = new SelectList(_context.Usuarios, "IdUsuario", "IdUsuario");
            return View();
        }

        // POST: Juradoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdJurado,IdUsuario,IdConcurso")] Jurado jurado)
        {
            if (ModelState.IsValid)
            {
                _context.Add(jurado);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdConcurso"] = new SelectList(_context.Concursos, "IdConcurso", "IdConcurso", jurado.IdConcurso);
            ViewData["IdUsuario"] = new SelectList(_context.Usuarios, "IdUsuario", "IdUsuario", jurado.IdUsuario);
            return View(jurado);
        }

        // GET: Juradoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jurado = await _context.Jurados.FindAsync(id);
            if (jurado == null)
            {
                return NotFound();
            }
            ViewData["IdConcurso"] = new SelectList(_context.Concursos, "IdConcurso", "IdConcurso", jurado.IdConcurso);
            ViewData["IdUsuario"] = new SelectList(_context.Usuarios, "IdUsuario", "IdUsuario", jurado.IdUsuario);
            return View(jurado);
        }

        // POST: Juradoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdJurado,IdUsuario,IdConcurso")] Jurado jurado)
        {
            if (id != jurado.IdJurado)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(jurado);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!JuradoExists(jurado.IdJurado))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdConcurso"] = new SelectList(_context.Concursos, "IdConcurso", "IdConcurso", jurado.IdConcurso);
            ViewData["IdUsuario"] = new SelectList(_context.Usuarios, "IdUsuario", "IdUsuario", jurado.IdUsuario);
            return View(jurado);
        }

        // GET: Juradoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var jurado = await _context.Jurados
                .Include(j => j.IdConcursoNavigation)
                .Include(j => j.IdUsuarioNavigation)
                .FirstOrDefaultAsync(m => m.IdJurado == id);
            if (jurado == null)
            {
                return NotFound();
            }

            return View(jurado);
        }

        // POST: Juradoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var jurado = await _context.Jurados.FindAsync(id);
            if (jurado != null)
            {
                _context.Jurados.Remove(jurado);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool JuradoExists(int id)
        {
            return _context.Jurados.Any(e => e.IdJurado == id);
        }
    }
}

WebApplication9/Controllers/PremiosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication9.Models;

namespace WebApplication9.Controllers
{
    public class PremiosController : Controller
    {
        private readonly SistemaDeConcursosContext _context;

        public PremiosController(SistemaDeConcursosContext context)
        {
            _context = context;
        }

        // GET: Premios
        public async Task<IActionResult> Index()
        {
            var sistemaDeConcursosContext = _context.Premios.Include(p => p.IdConcursoNavigation);
            return View(await sistemaDeConcursosContext.ToListAsync());
        }

        // GET: Premios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var premio = await _context.Premios
                .Include(p => p.IdConcursoNavigation)
                .FirstOrDefaultAsync(m => m.IdPremio == id);
            if (premio == null)
            {
                return NotFound();
            }

            return View(premio);
        }

        // GET: Premios/Create
        public IActionResult Create()
        {
            ViewData["IdConcurso"] = new SelectList(_context.Concursos, "IdConcurso", "IdConcurso");
            return View();
        }

        // POST: Premios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdPremio,IdConcurso,Descripcion,Cantidad")] Premio premio)
        {
            if (ModelState.IsValid)
            {
                _context.Add(premio);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdConcurso"] = new SelectList(_context.Concursos, "IdConcurso", "IdConcurso", premio.IdConcurso);
            return View(premio);
        }

        // GET: Premios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var premio = await _context.Premios.FindAsync(id);
            if (premio == null)
            {
                return NotFound();
            }
            ViewData["IdConcurso"] = new SelectList(_context.Concursos, "IdConcurso", "IdConcurso", premio.IdConcurso);
            return View(premio);
        }

        // POST: Premios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdPremio,IdConcurso,Descripcion,Cantidad")] Premio premio)
        {
            if (id != premio.IdPremio)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(premio);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PremioExists(premio.IdPremio))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdConcurso"] = new SelectList(_context.Concursos, "IdConcurso", "IdConcurso", premio.IdConcurso);
            return View(premio);
        }

        // GET: Premios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var premio = await _context.Premios
                .Include(p => p.IdConcursoNavigation)
                .FirstOrDefaultAsync(m => m.IdPremio == id);
            if (premio == null)
            {
                return NotFound();
            }

            return View(premio);
        }

        // POST: Premios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var premio = await _context.Premios.FindAsync(id);
            if (premio != null)
            {
                _context.Premios.Remove(premio);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PremioExists(int id)
        {
            return _context.Premios.Any(e => e.IdPremio == id);
        }
    }
}

WebApplication9/Controllers/UsuariosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WebApplication9.Models;

namespace WebApplication9.Controllers
{
    public class UsuariosController : Controller
    {
        private readonly SistemaDeConcursosContext _context;

        public UsuariosController(SistemaDeConcursosContext context)
        {
            _context = context;
        }

        // GET: Usuarios
        public async Task<IActionResult> Index()
        {
            return View(await _context.Usuarios.ToListAsync());
        }

        // GET: Usuarios/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // GET: Usuarios/Create
        public IActionResult Create()

        {
            ViewBag.TipoUsuarioOptions = new SelectList(new List<string> { "Jurado", "Participante", "Administrador" });

            return View();
        }

        // POST: Usuarios/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdUsuario,Nombre,Email,Contraseña,TipoUsuario,FechaRegistro")] Usuario usuario)
        {
            if (ModelState.IsValid)
            {
                _context.Add(usuario);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario == null)
            {
                return NotFound();
            }
            return View(usuario);
        }

        // POST: Usuarios/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdUsuario,Nombre,Email,Contraseña,TipoUsuario,FechaRegistro")] Usuario usuario)
        {
            if (id != usuario.IdUsuario)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(usuario);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!UsuarioExists(usuario.IdUsuario))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(usuario);
        }

        // GET: Usuarios/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var usuario = await _context.Usuarios
                .FirstOrDefaultAsync(m => m.IdUsuario == id);
            if (usuario == null)
            {
                return NotFound();
            }

            return View(usuario);
        }

        // POST: Usuarios/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var usuario = await _context.Usuarios.FindAsync(id);
            if (usuario != null)
            {
                _context.Usuarios.Remove(usuario);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool UsuarioExists(int id)
        {
            return _context.Usuarios.Any(e => e.IdUsuario == id);
        }
    }
}

WebApplication9/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication9</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WebApplication9.styles.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" />
</head>
<body>
    @using Microsoft.AspNetCore.Http
    @{
        // Obtener el rol del usuario desde la sesión, si no está autenticado se considera como "Guest"
        string userRole = Context.Session.GetString("UserRole") ?? "Guest";
        bool isAuthenticated = !string.IsNullOrEmpty(userRole) && userRole != "Guest";
    }

    <!-- Solo muestra la barra de navegación si el usuario está autenticado -->
    @if (isAuthenticated)
    {
        <div class="navigation">
            <ul>
                <li>

                </li>
                <li>
                    <a asp-controller="Home" asp-action="Index">
                        <span class="icon">
                            <ion-icon name="home-outline"></ion-icon>
                        </span>
                        <span class="title">Inicio</span>
                    </a>
                </li>

                @if (userRole == "admin" || userRole == "jurado")
                {
                    <li>
                        <a asp-controller="Categoría" asp-action="Index">
                            <span class="icon">
                                <ion-icon name="list-outline"></ion-icon>
                            </span>
                            <span class="title">Categorías</span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="TiposDeConcursoes" asp-action="Index">
                            <span class="icon">
                                <ion-icon name="trophy-outline"></ion-icon>
                            </span>
                            <span class="title">Tipos de Concurso</span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Concursoes" asp-action="Index">
                            <span class="icon">
                                <ion-icon name="ribbon-outline"></ion-icon>
                            </span>
                            <span class="title">Concursos</span>
                        </a>
                    </li>
                }

                @if (userRole == "admin" || userRole == "participante")
                {
                    <li>
                        <a asp-controller="Inscripciones" asp-action="Index">
                            <span class="icon">
                                <ion-icon name="checkmark-outline"></ion-icon>
                            </span>
                            <span class="title">Inscripciones</span>
                        </a>
                    </li>
                }

                @if (userRole == "admin" || userRole == "jurado")
                {
                    <li>
                        <a asp-controller="Juradoes" asp-action="Index">
                            <span class="icon">
                                <ion-icon name="school-outline"></ion-icon>
                            </span>
                            <span class="title">Jurado</span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="PuntuacionesJuradoes" asp-action="Index">
                            <span class="icon">
                                <ion-icon name="star-outline"></ion-icon>
                            </span>
                            <span class="title">Puntuaciones Jurados</span>
                        </a>
                    </li>
                }

                @if (userRole == "admin")
                {
                    <li>
                        <a asp-controller="Premios" asp-action="Index">
                            <span class="icon">
                                <ion-icon name="gift-outline"></ion-icon>
                            </span>
                            <span class="title">Premios</span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Resultadoes" asp-action="Index">
                            <span class="icon">
                                <ion-icon name="podium-outline"></ion-icon>
                            </span>
                            <span class="title">Resultados</span>
                        </a>
                    </li>

                    <li>
                        <a asp-controller="Usuarios" asp-action="Index">
                            <span class="icon">
                                <ion-icon name="people-outline"></ion-icon>
                            </span>
                            <span class="title">Usuarios</span>
                        </a>
                    </li>
                }

                <li>
                    <a asp-controller="Login" asp-action="Logout">
                        <span class="icon">
                            <ion-icon name="log-out-outline"></ion-icon>
                        </span>
                        <span class="title">Cerrar Sesión</span>
                    </a>
                </li>
            </ul>
        </div>
    }

    <!-- Contenido principal de la página -->
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script type="module" src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js"></script>
    <script nomodule src="https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>